### ISSUE TITLE
Type, Architecture and Libraries 

### ISSUE THREAD

**Issue by Mak-Ta-Reque** [mir-abir-hossain/real-history-of-Bangladesh#4]
Any plan to use LlamaIndex and LLAMA or LangChain with OpenAI api. I prefer open source model. Would be nice to design the architecture. Web app or Desktop app?

**Comment by mir-abir-hossain** [comment]
my personal preference -- using all open source.
i think people will prefer web app, as downloading something in desktop still feels uncomfortable to a lot of people i guess. But I don't about the cost associated with keeping a web app.

**Comment by dg1223** [comment]
Web App would be the most user-friendly solution. Our goal is to give people a convenient way to access Bangladesh's history. A web app will probably provide the least friction in terms of data access.

**Comment by dg1223** [comment]
There will be some cost to this nonetheless. Hosting on major cloud platforms like AWS, Azure or GCP would be the easiest solution but probably the most expensive as well. We can use hosting services like Netlify or Vercel as well but I am not sure how conveniently or robustly they scale. We'll have to do some options analysis on these stuff.

Let's get together on a meeting and discuss the plan, our team and our technical strengths.

**Comment by mir-abir-hossain** [comment]
we can call a online meeting. may be on google meeting. I think we should announce it on face book, as not everyone is yet active here.

**Comment by dg1223** [comment]
Sounds good. I guess you can do another call-to-action either through your Facebook post that garnered interests from the community or make a new post. Ask those who are truly interested to spend some time and effort to join this repo. Then we can schedule a Google meet at a time that would be convenient for everyone. Feel free to tag me (Shamir Alavi) in your comment or post. I'll also chime in.

I want to do this seriously as an end-to-end project because I believe it's relevant, timely, and will have a real impact. But if we want to do this seriously, we need to understand how many of us are willing to work on this and what our strengths.and weaknesses are. Usually, everyone will have more interest in doing the interesting parts like RAG, OCR etc. but the tedious and boring parts are the ones that would help us glue it all together as a product. We need to think about expenses too. So, we need to build a proper team that can develop, test, deploy and maintain your idea as a product.

Let's get people together and start working on it.

**Comment by mdabir1203** [comment]
I agree with most of the words here. I believe this is so relevant with the current realm in tech field. I can bring a lot of tools to help people out here with opensource models :)

**Comment by dg1223** [comment]
@mir-abir-hossain I believe we can close this one too as the discussion is done.
